#!/usr/bin/env python3
"""Generate speck_rounds.c

Reads the group keys from speck.h (the single source of truth) and emits the
1408 round functions (64 groups x 22 rounds) with their round keys baked in.
Run it by hand (it is NOT invoked by make):

    ./gen_speck.py > speck_rounds.c
"""
import re
import sys

ROUNDS = 22
ALPHA, BETA = 7, 2

def rotr16(x, r): return ((x >> r) | (x << (16 - r))) & 0xFFFF
def rotl16(x, r): return ((x << r) | (x >> (16 - r))) & 0xFFFF

def schedule(key):
    rk = [0] * ROUNDS
    l = [0] * (ROUNDS + 3)
    rk[0] = key[0]
    l[0], l[1], l[2] = key[1], key[2], key[3]
    for i in range(ROUNDS - 1):
        l[i + 3] = ((rk[i] + rotr16(l[i], ALPHA)) ^ i) & 0xFFFF
        rk[i + 1] = (rotl16(rk[i], BETA) ^ l[i + 3]) & 0xFFFF
    return rk

def read_keys(path="speck.h"):
    text = open(path).read()
    m = re.search(r'speck_keys\s*\[[^\]]*\]\s*\[[^\]]*\]\s*=\s*\{(.*?)\};',
                  text, re.S)
    if not m:
        sys.exit("gen_speck.py: could not find speck_keys[] in " + path)
    rows = re.findall(r'\{([^}]*)\}', m.group(1))
    keys = [[int(x, 16) for x in re.findall(r'0x[0-9a-fA-F]+', row)]
            for row in rows]
    if not keys or any(len(k) != 4 for k in keys):
        sys.exit("gen_speck.py: malformed speck_keys[] in " + path)
    return keys

PREAMBLE = r'''// AUTO-GENERATED by gen_speck.py from the keys in speck.h -- do not edit.
// Speck32/64 round functions: 64 groups x 22 rounds, round-major layout.
// Regenerate with:  ./gen_speck.py > speck_rounds.c

#include "speck.h"
#ifndef SPECK_NOPS
#define SPECK_NOPS 16
#endif
#define SPECK_STR2(x) #x
#define SPECK_STR(x) SPECK_STR2(x)
#define SPECK_PAD __asm__ volatile(".rept " SPECK_STR(SPECK_NOPS) "\n\tnop\n\t.endr")

#define SPECK_ATTR(align)                                                      \
    __attribute__((aligned(align), section(".speck"), noinline, used))

#define SPECK_BODY(key)                                                        \
    uint16_t x = (uint16_t)(in >> 16);                                         \
    uint16_t y = (uint16_t)in;                                                 \
    x = speck_rotr(x, SPECK_ALPHA);                                            \
    x = (uint16_t)(x + y);                                                     \
    x ^= (key);                                                                \
    y = speck_rotl(y, SPECK_BETA);                                             \
    y ^= x;                                                                    \
    SPECK_PAD

// Non-final round: recursively call the next round with the updated block.
#define SPECK_ROUND_AT(name, key, next, align)                                 \
    SPECK_ATTR(align) static block name(block in) {                            \
        SPECK_BODY(key);                                                       \
        return next(((block)x << 16) | y);                                     \
    }
// Final round: return the ciphertext (unwinds back to the caller).
#define SPECK_ROUND_LAST_AT(name, key, align)                                  \
    SPECK_ATTR(align) static block name(block in) {                            \
        SPECK_BODY(key);                                                       \
        return ((block)x << 16) | y;                                           \
    }

#define SPECK_ROUND(name, key, next) SPECK_ROUND_AT(name, key, next, 64)
#define SPECK_ROUND_FIRST(name, key, next) SPECK_ROUND_AT(name, key, next, 4096)
#define SPECK_ROUND_LAST(name, key) SPECK_ROUND_LAST_AT(name, key, 64)
'''

def main():
    keys = read_keys()
    n = len(keys)
    rk = [schedule(k) for k in keys]

    out = [PREAMBLE, ""]
    out.append("// forward declarations (each round recursively calls the next)")
    for r in range(ROUNDS):
        for g in range(n):
            out.append("static block speck_g%d_r%d(block);" % (g, r))
    out.append("")

    for r in range(ROUNDS):
        for g in range(n):
            if r == ROUNDS - 1:
                out.append("SPECK_ROUND_LAST(speck_g%d_r%d, 0x%04x)" % (g, r, rk[g][r]))
            elif r == 0 and g == 0:
                out.append("SPECK_ROUND_FIRST(speck_g%d_r%d, 0x%04x, speck_g%d_r%d)" % (g, r, rk[g][r], g, r + 1))
            else:
                out.append("SPECK_ROUND(speck_g%d_r%d, 0x%04x, speck_g%d_r%d)" % (g, r, rk[g][r], g, r + 1))
    out.append("")

    out.append("// head of each group's chain (round 0); calling it runs all 22 rounds")
    out.append("block (*const speck_group_heads[SPECK_NUM_GROUPS])(block) = {")
    for g in range(n):
        out.append("    speck_g%d_r0," % g)
    out.append("};")
    print("\n".join(out))

if __name__ == "__main__":
    main()
